# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  minify:
    cmds:
      - |
        html-minifier-terser --collapse-whitespace \
        --remove-comments --remove-optional-tags --remove-redundant-attributes \
        --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype \
        --minify-css true --minify-js true index.html -o index.min.html
